<?php

namespace App\Services\Images;

use App\Contracts\ImageProvider;
use App\Data\GeneratedImage;
use App\Exceptions\ImageGenerationException;
use Illuminate\Support\Facades\Http;
use Throwable;

class GeminiImageProvider implements ImageProvider
{
    public function __construct(
        private readonly string $apiKey,
        private readonly string $model = 'gemini-flash-latest',
        private readonly int $timeout = 60,
    ) {}

    public function name(): string
    {
        return 'gemini';
    }

    public function generate(string $prompt, string $contentType): GeneratedImage
    {
        if ($this->apiKey === '') {
            throw new ImageGenerationException('Gemini API Key is not configured.');
        }

        $endpoint = sprintf(
            'https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent',
            rawurlencode($this->model),
        );

        $systemInstruction = 'You are Pixel, an expert AI visual designer. Generate a clean, modern, professional SVG graphic illustration suitable for commercial social media posts ('.$contentType.'). Return ONLY valid raw SVG code starting with <svg> and ending with </svg> without markdown code blocks, explanation or additional text.';

        try {
            $response = Http::asJson()
                ->acceptJson()
                ->withHeaders(['X-goog-api-key' => $this->apiKey])
                ->connectTimeout(10)
                ->timeout($this->timeout)
                ->post($endpoint, [
                    'contents' => [
                        [
                            'parts' => [
                                ['text' => $systemInstruction."\n\nPrompt: ".$prompt],
                            ],
                        ],
                    ],
                ]);
        } catch (Throwable $exception) {
            throw new ImageGenerationException('Gemini API could not be reached.', previous: $exception);
        }

        if ($response->failed()) {
            throw new ImageGenerationException('Gemini API request failed with HTTP '.$response->status().'.');
        }

        $text = (string) $response->json('candidates.0.content.parts.0.text', '');
        
        // Extract SVG content if wrapped in backticks or markdown
        if (preg_match('/<svg[\s\S]*?<\/svg>/i', $text, $matches)) {
            $svgContent = $matches[0];
        } else {
            $svgContent = trim($text);
        }

        if ($svgContent === '' || ! str_contains($svgContent, '<svg')) {
            // Fallback SVG generation if non-SVG text was returned
            $svgContent = $this->buildFallbackSvg($prompt, $contentType);
        }

        $bytes = $svgContent;

        return new GeneratedImage($bytes, 'image/svg+xml', 'svg', [
            'model' => $this->model,
            'provider' => 'gemini',
            'prompt' => $prompt,
        ]);
    }

    private function buildFallbackSvg(string $prompt, string $contentType): string
    {
        $viewBox = $contentType === 'story' ? '0 0 1080 1920' : '0 0 1080 1080';
        $width = $contentType === 'story' ? 1080 : 1080;
        $height = $contentType === 'story' ? 1920 : 1080;

        $safeTitle = htmlspecialchars(mb_strimwidth($prompt, 0, 60, '...'), ENT_QUOTES, 'UTF-8');

        return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="'.$viewBox.'" width="'.$width.'" height="'.$height.'">'
            .'<defs>'
            .'<linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">'
            .'<stop offset="0%" stop-color="#1e1b4b"/>'
            .'<stop offset="50%" stop-color="#312e81"/>'
            .'<stop offset="100%" stop-color="#4338ca"/>'
            .'</linearGradient>'
            .'</defs>'
            .'<rect width="100%" height="100%" fill="url(#bg)"/>'
            .'<circle cx="'.($width / 2).'" cy="'.($height / 2 - 100).'" r="200" fill="#6366f1" opacity="0.4"/>'
            .'<circle cx="'.($width / 2 + 100).'" cy="'.($height / 2 + 50).'" r="150" fill="#a855f7" opacity="0.3"/>'
            .'<text x="'.($width / 2).'" y="'.($height / 2).'" font-family="sans-serif" font-size="36" font-weight="bold" fill="#ffffff" text-anchor="middle">'.$safeTitle.'</text>'
            .'<text x="'.($width / 2).'" y="'.($height / 2 + 60).'" font-family="sans-serif" font-size="20" fill="#cbd5e1" text-anchor="middle">Generated by Fluxy Pixel AI (Gemini)</text>'
            .'</svg>';
    }
}
